# Generated by Django 5.1.4 on 2025-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.SmallIntegerField(default=0)),
                ('movieID1', models.SmallIntegerField(default=0)),
                ('movieID2', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
