# Generated by Django 5.1.4 on 2025-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.SmallIntegerField(default=0),
        ),
    ]
